plugins = []
headers = []

[functions]

[functions."*"]

[build]
publish = "C:\\Users\\허재윤\\Desktop\\클로드\\클로드코드 비브레\\프로그램 개발\\트레이너 수업일지\\깃허브"
publishOrigin = "default"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[redirects]]
from = "/manual.html"
to = "https://app.heobotss.com/manual.html"
status = 301.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]